__package_name__ = "juno_assembly"
__authors__ = "Alejandra Hernández Segura and Karim Hajji"
__email__ = "karim.hajji@rivm.nl"
__license__ = "AGPLv3"
__version__ = "2.1.0"
__description__ = "Juno Assembly does reference free assembly for bacteria."
