__package_name__ = "juno_assembly"
__authors__ = "Alejandra Hernández Segura and Karim Hajji"
__email__ = "karim.hajji@rivm.nl"
__license__ = "AGPLv3"
__version__ = "3.0.0"
__description__ = "Juno-assembly pipeline for de novo assembly of paired Illumina WGS data from haploid organisms"
